import type { Product } from "./PriceCard";

export type ProductWithCheckout = Product & { checkoutUrl?: string };

const checkoutLinks = {
  weekly: import.meta.env.VITE_CHECKOUT_LINK_WEEKLY as string | undefined,
  monthly: import.meta.env.VITE_CHECKOUT_LINK_MONTHLY as string | undefined,
  quarterly: import.meta.env.VITE_CHECKOUT_LINK_QUARTERLY as string | undefined,
  semiannual: import.meta.env.VITE_CHECKOUT_LINK_SEMIANNUAL as string | undefined,
  lifetime: import.meta.env.VITE_CHECKOUT_LINK_LIFETIME as string | undefined,
};

const buildPrice = (
  productId: string,
  cents: number,
  currency: string,
  recurringInterval?: string | null
) => ({
  id: `${productId}-price`,
  productId,
  createdAt: "static",
  modifiedAt: null,
  isArchived: false,
  priceAmount: cents,
  priceCurrency: currency,
  recurringInterval,
});

export const staticProducts: ProductWithCheckout[] = [
  {
    id: "premium-weekly",
    name: "Premium Weekly",
    description: "Flexible weekly billing for short-term use.",
    isRecurring: true,
    recurringInterval: "week",
    medias: [],
    metadata: {},
    organizationId: "static",
    createdAt: "static",
    modifiedAt: null,
    isArchived: false,
    prices: [buildPrice("premium-weekly", 999, "USD", "week")],
    checkoutUrl: checkoutLinks.weekly,
  },
  {
    id: "premium-monthly",
    name: "Premium Monthly",
    description: "Standard monthly subscription with full access.",
    isRecurring: true,
    recurringInterval: "month",
    medias: [],
    metadata: {},
    organizationId: "static",
    createdAt: "static",
    modifiedAt: null,
    isArchived: false,
    prices: [buildPrice("premium-monthly", 2999, "USD", "month")],
    checkoutUrl: checkoutLinks.monthly,
  },
  {
    id: "premium-quarterly",
    name: "Premium Quarterly",
    description: "Quarterly billing with a small discount.",
    isRecurring: true,
    recurringInterval: "quarter",
    medias: [],
    metadata: {},
    organizationId: "static",
    createdAt: "static",
    modifiedAt: null,
    isArchived: false,
    prices: [buildPrice("premium-quarterly", 7999, "USD", "quarter")],
    checkoutUrl: checkoutLinks.quarterly,
  },
  {
    id: "premium-semiannual",
    name: "Premium Semiannual",
    description: "Pay twice a year and save compared to monthly.",
    isRecurring: true,
    recurringInterval: "6 months",
    medias: [],
    metadata: {},
    organizationId: "static",
    createdAt: "static",
    modifiedAt: null,
    isArchived: false,
    prices: [buildPrice("premium-semiannual", 14999, "USD", "6 months")],
    checkoutUrl: checkoutLinks.semiannual,
  },
  {
    id: "premium-lifetime",
    name: "Lifetime Premium",
    description: "One-time purchase; keep access forever.",
    isRecurring: false,
    recurringInterval: null,
    medias: [],
    metadata: {},
    organizationId: "static",
    createdAt: "static",
    modifiedAt: null,
    isArchived: false,
    prices: [buildPrice("premium-lifetime", 5900, "USD", null)],
    checkoutUrl: checkoutLinks.lifetime,
  },
];
